Finished
mate-academy/react_keyboard-hooks pull request #19
Opened 2023-01-19 12:22 UTC by JzSol

[DEMO LINK](https://JzSol.github.io/react_keyboard/)

2023-01-20 10:22 UTC, SalehBUD approved these changes

2023-01-20 10:22 UTC, SalehBUD commented on src/App.tsx
> +        {key ? `The last pressed key is [${key}]` : `Nothing was pressed yet`}
```suggestion
        {key ? `The last pressed key is [${key}]` : 'Nothing was pressed yet'}
```

2023-01-20 11:42 UTC, meforoma commented on src/App.tsx
> +  });
it's reasonable to cleanup before component unmounts
```suggestion
  useEffect(() => {
    document.addEventListener('keyup', pressedKey);
    
    return () => document.removeEventListener('keyup', pressedKey);
  }, []);
```

2023-01-20 11:42 UTC, meforoma requested changes
see the comment

2023-01-25 12:57 UTC, naziamoff approved these changes
gj, just one suggestion

2023-01-25 12:57 UTC, naziamoff commented on src/App.tsx
> +        {key ? `The last pressed key is [${key}]` : 'Nothing was pressed yet'}
keep ternaries multilined

2023-05-04 08:50 UTC, meforoma approved these changes

2026-05-16 06:31 UTC, closed without merging